name: ColorPortals
author: Tanner Embry (SnowGears)
description: Create physical portals in-game!
version: 1.6.6
api-version: 1.13
main: com.snowgears.colorportals.ColorPortals
softdepend: [Multiverse-Core]
permissions:
    colorportals.use.*:
        description: Allows player to use all color portals
        default: op
    colorportals.create.*:
        description: Allows player to create all color portals
        default: op
    colorportals.destroy.*:
        description: Allows player to destroy all color portals
        default: op
    colorportals.nodistance:
        description: Allows player to bypass max/min portal distance
        default: op
    colorportals.max.*:
        description:  Player is only allowed to make * number of portals (* is unlimited)
        default: op
commands:
   portal:
      description: Different commands pertaining to plugin
      usage: /<command>
   cp:
      description: Different commands pertaining to plugin
      usage: /<command>